config/routes.rb
Gitlab::Application.routes.draw do


  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server.new, at: '/info/resque'

  get 'help' => 'help#index'
  get 'help/permissions' => 'help#permissions'
  get 'help/workflow' => 'help#workflow'

  namespace :admin do
    resources :users do 
      member do 
        put :team_update
      end
    end
    resources :projects, :constraints => { :id => /[^\/]+/ } do 
      member do 
        get :team
        put :team_update
      end
    end
    resources :team_members, :only => [:edit, :update, :destroy]
    get 'emails', :to => 'mailer#preview'
    get 'mailer/preview_note'
    get 'mailer/preview_user_new'
    get 'mailer/preview_issue_new'
    root :to => "users#index"
  end

  get "errors/githost"
  get "profile/password", :to => "profile#password"
  put "profile/password", :to => "profile#password_update"
  put "profile/reset_private_token", :to => "profile#reset_private_token"
  get "profile", :to => "profile#show"
  get "profile/design", :to => "profile#design"
  put "profile/update", :to => "profile#update"

  get "dashboard", :to => "dashboard#index"
  get "dashboard/issues", :to => "dashboard#issues"
  get "dashboard/merge_requests", :to => "dashboard#merge_requests"

  #get "profile/:id", :to => "profile#show"

  resources :projects, :constraints => { :id => /[^\/]+/ }, :only => [:new, :create, :index]
  resources :keys

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks }

  resources :projects, :constraints => { :id => /[^\/]+/ }, :except => [:new, :create, :index], :path => "/" do
    member do
      get "team"
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, :only => [:show, :edit, :destroy, :create] do
      member do
        get "history"        
      end
    end

    resource :repository do 
      member do 
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, :only => [:index, :create, :destroy]

    resources :refs, :only => [], :path => "/" do 
      collection do 
        get "switch"
      end

      member do 
        get "tree", :constraints => { :id => /[a-zA-Z.\/0-9_\-]+/ }
        get "blob", 
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }


        # tree viewer
        get "tree/:path" => "refs#tree",
          :as => :tree_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }
      end
    end

    resources :merge_requests do 
      member do 
        get :diffs
      end
    end
    
    resources :snippets
    resources :hooks, :only => [:index, :new, :create, :destroy, :show] do 
      member do 
        get :test
      end
    end
    resources :commits do 
      collection do 
        get :compare
      end
    end
    resources :team_members
    resources :issues do
      collection do
        post  :sort
        get   :search
      end
    end
    resources :notes, :only => [:create, :destroy]
  end
  root :to => "projects#index"
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, :class_name => "User"
  belongs_to :assignee, :class_name => "User"
  has_many :notes, :as => :noteable, :dependent => :destroy

  attr_protected :author, :author_id, :project, :project_id

  validates_presence_of :project_id
  validates_presence_of :assignee_id
  validates_presence_of :author_id

  delegate :name,
           :email,
           :to => :author,
           :prefix => true

  delegate :name,
           :email,
           :to => :assignee,
           :prefix => true

  validates :title,
            :presence => true,
            :length   => { :within => 0..255 }

  scope :critical, where(:critical => true)
  scope :non_critical, where(:critical => false)

  scope :opened, where(:closed => false)
  scope :closed, where(:closed => true)
  scope :assigned, lambda { |u| where(:assignee_id => u.id)}

  acts_as_list

  def self.open_for(user)
    opened.assigned(user)
  end

  def today?
    Date.today == created_at.to_date
  end

  def new?
    today? && created_at == updated_at
  end
end
# == Schema Information
#
# Table name: issues
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  assignee_id :integer
#  author_id   :integer
#  project_id  :integer
#  created_at  :datetime
#  updated_at  :datetime
#  closed      :boolean         default(FALSE), not null
#  position    :integer         default(0)
#  critical    :boolean         default(FALSE), not null
#  branch_name :string(255)
#

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :project
  before_filter :module_enabled
  before_filter :issue, :only => [:edit, :update, :destroy, :show]
  layout "project"

  # Authorize
  before_filter :add_project_abilities

  # Allow read any issue
  before_filter :authorize_read_issue!

  # Allow write(create) issue
  before_filter :authorize_write_issue!, :only => [:new, :create]

  # Allow modify issue
  before_filter :authorize_modify_issue!, :only => [:close, :edit, :update, :sort]

  # Allow destroy issue
  before_filter :authorize_admin_issue!, :only => [:destroy]

  respond_to :js, :html

  def index
    @issues = case params[:f].to_i
              when 1 then @project.issues
              when 2 then @project.issues.closed
              when 3 then @project.issues.opened.assigned(current_user)
              else @project.issues.opened
              end

    @issues = @issues.includes(:author, :project)

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.atom { render :layout => false }
    end
  end

  def new
    @issue = @project.issues.new
    respond_with(@issue)
  end

  def edit
    respond_with(@issue)
  end

  def show
    @notes = @issue.notes.inc_author.order("created_at DESC").limit(20)
    @note = @project.notes.new(:noteable => @issue)

    @commits = if @issue.branch_name && @project.repo.heads.map(&:name).include?(@issue.branch_name)
                 @project.repo.commits_between("master", @issue.branch_name)
               else 
                 []
               end


    respond_to do |format|
      format.html
      format.js { respond_with_notes }
    end
  end

  def create
    @issue = @project.issues.new(params[:issue])
    @issue.author = current_user
    @issue.save

    respond_with(@issue)
  end

  def update
    @issue.update_attributes(params[:issue])

    respond_to do |format|
      format.js
      format.html { redirect_to [@project, @issue]}
    end
  end

  def destroy
    return access_denied! unless can?(current_user, :admin_issue, @issue)

    @issue.destroy

    respond_to do |format|
      format.html { redirect_to project_issues_path }
      format.js { render :nothing => true }
    end
  end

  def sort
    @issues = @project.issues.where(:id => params['issue'])
    @issues.each do |issue|
      issue.position = params['issue'].index(issue.id.to_s) + 1
      issue.save
    end

    render :nothing => true
  end

  def search
    terms = params['terms']

    @project  = Project.find(params['project'])
    @issues   = case params[:status].to_i
                  when 1 then @project.issues
                  when 2 then @project.issues.closed
                  when 3 then @project.issues.opened.assigned(current_user)
                  else @project.issues.opened
                end

    @issues = @issues.where("title LIKE ?", "%#{terms}%") unless terms.blank?

    render :partial => 'issues'
  end

  protected

  def issue
    @issue ||= @project.issues.find(params[:id])
  end

  def authorize_modify_issue!
    return render_404 unless can?(current_user, :modify_issue, @issue)
  end

  def authorize_admin_issue!
    return render_404 unless can?(current_user, :admin_issue, @issue)
  end

  def module_enabled
    return render_404 unless @project.issues_enabled
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def sort_class
    if can?(current_user, :admin_issue, @project) && (!params[:f] || params[:f] == "0")
                        "handle"
    end
  end

  def project_issues_filter_path project, params = {}
    params[:f] ||= cookies['issue_filter']
    project_issues_path project, params
  end

  def link_to_issue_assignee(issue)
    project = issue.project

    tm = project.team_member_by_id(issue.assignee_id)
    if tm
      link_to issue.assignee_name, project_team_member_path(project, tm), :class => "author_link"
    else
      issue.assignee_name
    end
  end

  def link_to_issue_author(issue)
    project = issue.project

    tm = project.team_member_by_id(issue.author_id)
    if tm
      link_to issue.author_name, project_team_member_path(project, tm), :class => "author_link"
    else
      issue.author_name
    end
  end
end

app/views/issues/_form.html.haml
%div.issue-form-holder
  = form_for [@project, @issue], :remote => request.xhr? do |f|
    %h3= @issue.new_record? ? "New Issue" : "Edit Issue ##{@issue.id}"
    %hr
    -if @issue.errors.any?
      .alert-message.block-message.error
        %ul
          - @issue.errors.full_messages.each do |msg|
            %li= msg

    .clearfix
      = f.label :assignee_id
      .input= f.select(:assignee_id, @project.users.all.collect {|p| [ p.name, p.id ] }, { :include_blank => "Select user" })

    .clearfix
      = f.label :critical, "Critical"
      .input= f.check_box :critical
    
    - unless @issue.new_record?
      .clearfix
        = f.label :closed
        .input= f.check_box :closed

    .clearfix
      = f.label :title
      .input= f.text_area :title, :maxlength => 255, :class => "xxlarge"
    .actions
      = f.submit 'Save', :class => "primary btn"

      - if request.xhr?
        = link_to "Cancel", "#back", :onclick => "backToIssues();", :class => "btn" 
      - else 
        - if @issue.new_record?
          = link_to "Cancel", project_issues_path(@project), :class => "btn"
        - else    
          = link_to "Cancel", project_issue_path(@project, @issue), :class => "btn"


      - unless @issue.new_record?
        .right
          = link_to 'Remove', [@project, @issue], :confirm => 'Are you sure?', :method => :delete, :class => "danger btn"

app/views/issues/_head.html.haml
.tabs
  %li{:class => "#{'active' if current_page?(project_issues_path(@project))}"}
    = link_to project_issues_path(@project), :class => "tab" do 
      Issues  

app/views/issues/_issues.html.haml
- @issues.critical.each do |issue|
  = render(:partial => 'issues/show', :locals => {:issue => issue})

- @issues.non_critical.each do |issue|
  = render(:partial => 'issues/show', :locals => {:issue => issue})

app/views/issues/_show.html.haml
%li.wll{ :id => dom_id(issue), :class => "issue #{issue.critical ? "critical" : ""}", :url => project_issue_path(issue.project, issue) }
  .right
    - if can? current_user, :modify_issue, issue
      - if issue.closed
        = link_to 'Reopen', project_issue_path(issue.project, issue, :issue => {:closed => false }, :status_only => true), :method => :put,  :class => "btn small", :remote => true
      - else
        = link_to 'Resolve', project_issue_path(issue.project, issue, :issue => {:closed => true }, :status_only => true), :method => :put, :class => "success btn small", :remote => true
      = link_to 'Edit', edit_project_issue_path(issue.project, issue), :class => "btn small edit-issue-link", :remote => true
    -#- if can?(current_user, :admin_issue, @project) || issue.author == current_user
      = link_to 'Remove', [issue.project, issue], :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => "danger btn small delete-issue", :id => "destroy_issue_#{issue.id}"
  = image_tag gravatar_icon(issue.assignee_email), :class => "avatar"
  %span.update-author
    assigned to
    %strong= issue.assignee_name
    - if issue.critical
      %span.label.important critical
    - if issue.today?
      %span.label.success today



  = link_to project_issue_path(issue.project, issue) do
    %p.row_title= truncate(issue.title, :length => 60)

app/views/issues/create.js.haml
- if @issue.valid?
  :plain
    switchFromNewIssue();
    $("#issues-table").prepend("#{escape_javascript(render(:partial => 'show', :locals => {:issue => @issue} ))}");
    $.ajax({type: "GET", url: location.href, dataType: "script"});
- else
  :plain
    $("#new_issue_dialog").empty();
    $("#new_issue_dialog").append("#{escape_javascript(render('form'))}");
    $('select#issue_assignee_id').chosen();

app/views/issues/edit.html.haml
= render "form"

:javascript 
  $(function(){ 
    $('select#issue_assignee_id').chosen();
  });

app/views/issues/edit.js.haml
:plain
  var edit_issue_dialog = $("<div id='edit_issue_dialog'></div>");
  edit_issue_dialog.html("#{escape_javascript(render('form'))}");
  switchToEditIssue(edit_issue_dialog);

app/views/issues/index.html.haml
.issues_content
  %h3
    Issues
    %span.rss-icon
      = link_to project_issues_path(@project, :atom, { :private_token => current_user.private_token }) do 
        = image_tag "Rss-UI.PNG", :width => 22, :title => "feed"

    - if can? current_user, :write_issue, @project
      = link_to new_project_issue_path(@project), :class => "right btn small", :title => "New Issue", :remote => true do 
        New Issue
  %hr
  %div#issues-table-holder.ui-box
    .title
      .row
        .span8
          %ul.pills.left
            %li{:class => ("active" if (params[:f] == "0" || !params[:f]))}
              = link_to project_issues_path(@project, :f => 0) do 
                Open
            %li{:class => ("active" if params[:f] == "2")}
              = link_to project_issues_path(@project, :f => 2) do 
                Closed
            %li{:class => ("active" if params[:f] == "3")}
              = link_to project_issues_path(@project, :f => 3) do 
                To Me
            %li{:class => ("active" if params[:f] == "1")}
              = link_to project_issues_path(@project, :f => 1) do 
                All

        .span3.right
          = form_tag search_project_issues_path(@project), :method => :get, :remote => true, :id => "issue_search_form", :class => :right  do
            = hidden_field_tag :project_id, @project.id, { :id => 'project_id' }
            = hidden_field_tag :status, params[:f]
            = search_field_tag :issue_search, nil, { :placeholder => 'Search', :class => 'issue_search' }

    %ul#issues-table.unstyled= render "issues"

:javascript
  var href       = $('.issue_search').parent().attr('action');
  var last_terms = '';

  $('.issue_search').keyup(function() {
    var terms       = $(this).val();
    var project_id  = $('#project_id').val();
    var status      = $('#status').val();
    if (terms != last_terms) {
      last_terms = terms;

      if (terms.length >= 2 || terms.length == 0) {
        $.get(href, { 'status': status, 'terms': terms, project: project_id  }, function(response) {
          $('#issues-table').html(response);
          setSortable();
        });
      }
    }
  });

  $('.delete-issue').live('ajax:success', function() {
    $(this).closest('tr').fadeOut(); updatePage();});

  function setSortable(){
    $('#issues-table').sortable({
      axis: 'y',
      dropOnEmpty: false,
      handle: '.handle',
      cursor: 'crosshair',
      items: 'tr',
      opacity: 0.4,
      scroll: true,
      update: function(){
        $.ajax({
        type: 'post',
        data: $('#issues-table').sortable('serialize'),
        dataType: 'script',
        complete: function(request){
          $('#issues-table').effect('highlight');
        },
        url: "#{sort_project_issues_path(@project)}"})
        }
      });
  }

  $(function(){
    setSortable();
  });

app/views/issues/index.js.haml
:plain
  $('#issues-table').html("#{escape_javascript(render('issues'))}");
  setSortable();

app/views/issues/new.html.haml
= render "form"

:javascript 
  $(function(){ 
    $('select#issue_assignee_id').chosen();
  });

app/views/issues/new.js.haml
:plain
  var new_issue_dialog = $("<div id='new_issue_dialog'></div>");
  new_issue_dialog.html("#{escape_javascript(render('form'))}");
  switchToNewIssue(new_issue_dialog);

app/views/issues/show.html.haml
%h3 
  Issue ##{@issue.id} 
  %small
    created at 
    = @issue.created_at.stamp("Aug 21, 2011")

  %span.right
    - if can?(current_user, :admin_project, @project) || @issue.author == current_user
      - if @issue.closed
        = link_to 'Reopen', project_issue_path(@project, @issue, :issue => {:closed => false }, :status_only => true), :method => :put,  :class => "btn"
      - else
        = link_to 'Close', project_issue_path(@project, @issue, :issue => {:closed => true }, :status_only => true), :method => :put, :class => "btn", :title => "Close merge request"
    - if can?(current_user, :admin_project, @project) || @issue.author == current_user
      = link_to edit_project_issue_path(@project, @issue), :class => "btn small" do 
        Edit

.back_link
  = link_to project_issues_path(@project) do 
    &larr; To issues list


%hr
- if @issue.closed
  .alert-message.error Closed
- else 
  .alert-message.success Open


%div.well
  %div
    %cite.cgray Created by
    = image_tag gravatar_icon(@issue.author_email), :width => 16, :class => "lil_av"
    %strong.author= link_to_issue_author(@issue)

    %cite.cgray and currently assigned to 
    = image_tag gravatar_icon(@issue.assignee_email), :width => 16, :class => "lil_av"
    %strong.author= link_to_issue_assignee(@issue)
      
    %hr
    
  %div= simple_format @issue.title


.issue_notes= render "notes/notes"

app/views/issues/show.js.haml
= render "notes/load"

app/views/issues/update.js.haml
- if params[:status_only]
  - if @issue.valid?
    :plain
      $("##{dom_id(@issue)}").fadeOut();
- else
  - if @issue.valid?
    :plain
      updatePage();
      switchFromEditIssue();
  - else
    :plain
      $("#edit_issue_dialog").empty();
      $("#edit_issue_dialog").append("#{escape_javascript(render('form'))}");
      $('select#issue_assignee_id').chosen();