config/routes.rb
Gitlab::Application.routes.draw do


  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server.new, at: '/info/resque'

  get 'help' => 'help#index'
  get 'help/permissions' => 'help#permissions'
  get 'help/workflow' => 'help#workflow'

  namespace :admin do
    resources :users do 
      member do 
        put :team_update
      end
    end
    resources :projects, :constraints => { :id => /[^\/]+/ } do 
      member do 
        get :team
        put :team_update
      end
    end
    resources :team_members, :only => [:edit, :update, :destroy]
    get 'emails', :to => 'mailer#preview'
    get 'mailer/preview_note'
    get 'mailer/preview_user_new'
    get 'mailer/preview_issue_new'
    root :to => "users#index"
  end

  get "errors/githost"
  get "profile/password", :to => "profile#password"
  put "profile/password", :to => "profile#password_update"
  put "profile/reset_private_token", :to => "profile#reset_private_token"
  get "profile", :to => "profile#show"
  get "profile/design", :to => "profile#design"
  put "profile/update", :to => "profile#update"

  get "dashboard", :to => "dashboard#index"
  get "dashboard/issues", :to => "dashboard#issues"
  get "dashboard/merge_requests", :to => "dashboard#merge_requests"

  #get "profile/:id", :to => "profile#show"

  resources :projects, :constraints => { :id => /[^\/]+/ }, :only => [:new, :create, :index]
  resources :keys

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks }

  resources :projects, :constraints => { :id => /[^\/]+/ }, :except => [:new, :create, :index], :path => "/" do
    member do
      get "team"
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, :only => [:show, :edit, :destroy, :create] do
      member do
        get "history"        
      end
    end

    resource :repository do 
      member do 
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, :only => [:index, :create, :destroy]

    resources :refs, :only => [], :path => "/" do 
      collection do 
        get "switch"
      end

      member do 
        get "tree", :constraints => { :id => /[a-zA-Z.\/0-9_\-]+/ }
        get "blob", 
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }


        # tree viewer
        get "tree/:path" => "refs#tree",
          :as => :tree_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }
      end
    end

    resources :merge_requests do 
      member do 
        get :diffs
      end
    end
    
    resources :snippets
    resources :hooks, :only => [:index, :new, :create, :destroy, :show] do 
      member do 
        get :test
      end
    end
    resources :commits do 
      collection do 
        get :compare
      end
    end
    resources :team_members
    resources :issues do
      collection do
        post  :sort
        get   :search
      end
    end
    resources :notes, :only => [:create, :destroy]
  end
  root :to => "projects#index"
end

app/views/widgets/_project_member.html.haml
- member = @project.team_member_by_id(current_user.id)
.widget
  .media-grid
    %li
      = link_to project_team_member_path(@project, member), :title => current_user.name do 
        = image_tag gravatar_icon(current_user.email, 60), :class => "thumbnail", :width => 60
  %h4
    Hey, 
    #{truncate current_user.first_name, :lenght => 24}!

  %p 
    - if @project.issues_enabled
      %span
        Assigned Issues:
        = current_user.assigned_issues.opened.count
      %br
    - if @project.merge_requests_enabled
      %span
        Assigned Requests:
        = current_user.assigned_merge_requests.opened.count
      %br
    %br
    - if @project.merge_requests_enabled && can?(current_user, :write_merge_request, @project)
      = link_to new_project_merge_request_path(@project), :title => "New Merge Request", :class => "btn small padded" do 
        Merge Request
    - if @project.issues_enabled && can?(current_user, :write_issue, @project)
      = link_to new_project_issue_path(@project), :title => "New Issue", :class => "btn small" do 
        Issue

  %hr
  %p
    Your access level in this project is 
    %code #{member.project_access_human}
    %br
    Visit member card for more information

  .link_holder
    = link_to project_team_member_path(@project, member), :title => current_user.name do 
      = "Member Card »"



-#- if can? current_user, :write_project, @project
  .widget
    - if @project.issues_enabled && @project.merge_requests_enabled
      .span3
        %p You have access to create new issue or merge request.
        %div
          = link_to new_project_issue_path(@project), :title => "New Issue", :class => "" do 
            New Issue »
        %div
          = link_to new_project_merge_request_path(@project), :title => "New Merge Request", :class => "" do 
            New Merge Request »

app/views/widgets/_recent_projects.html.haml
- if current_user.projects.count > 0
  %div.widget
    %h4
      Recent Projects:
    %ul
      - current_user.projects.order("id DESC").limit(5).each do |project|
        %li
          = link_to project_path(project) do
            = project.name
    .link_holder
      = link_to "Projects » ", projects_path