config/routes.rb
Gitlab::Application.routes.draw do


  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server.new, at: '/info/resque'

  get 'help' => 'help#index'
  get 'help/permissions' => 'help#permissions'
  get 'help/workflow' => 'help#workflow'

  namespace :admin do
    resources :users do 
      member do 
        put :team_update
      end
    end
    resources :projects, :constraints => { :id => /[^\/]+/ } do 
      member do 
        get :team
        put :team_update
      end
    end
    resources :team_members, :only => [:edit, :update, :destroy]
    get 'emails', :to => 'mailer#preview'
    get 'mailer/preview_note'
    get 'mailer/preview_user_new'
    get 'mailer/preview_issue_new'
    root :to => "users#index"
  end

  get "errors/githost"
  get "profile/password", :to => "profile#password"
  put "profile/password", :to => "profile#password_update"
  put "profile/reset_private_token", :to => "profile#reset_private_token"
  get "profile", :to => "profile#show"
  get "profile/design", :to => "profile#design"
  put "profile/update", :to => "profile#update"

  get "dashboard", :to => "dashboard#index"
  get "dashboard/issues", :to => "dashboard#issues"
  get "dashboard/merge_requests", :to => "dashboard#merge_requests"

  #get "profile/:id", :to => "profile#show"

  resources :projects, :constraints => { :id => /[^\/]+/ }, :only => [:new, :create, :index]
  resources :keys

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks }

  resources :projects, :constraints => { :id => /[^\/]+/ }, :except => [:new, :create, :index], :path => "/" do
    member do
      get "team"
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, :only => [:show, :edit, :destroy, :create] do
      member do
        get "history"        
      end
    end

    resource :repository do 
      member do 
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, :only => [:index, :create, :destroy]

    resources :refs, :only => [], :path => "/" do 
      collection do 
        get "switch"
      end

      member do 
        get "tree", :constraints => { :id => /[a-zA-Z.\/0-9_\-]+/ }
        get "blob", 
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }


        # tree viewer
        get "tree/:path" => "refs#tree",
          :as => :tree_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }
      end
    end

    resources :merge_requests do 
      member do 
        get :diffs
      end
    end
    
    resources :snippets
    resources :hooks, :only => [:index, :new, :create, :destroy, :show] do 
      member do 
        get :test
      end
    end
    resources :commits do 
      collection do 
        get :compare
      end
    end
    resources :team_members
    resources :issues do
      collection do
        post  :sort
        get   :search
      end
    end
    resources :notes, :only => [:create, :destroy]
  end
  root :to => "projects#index"
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :authenticate_admin!

  def index
    @admin_projects = Project.page(params[:page])
  end

  def show
    @admin_project = Project.find_by_code(params[:id])

    @users = if @admin_project.users.empty?
               User
             else
               User.not_in_project(@admin_project)
             end.all
  end

  def new
    @admin_project = Project.new
  end

  def edit
    @admin_project = Project.find_by_code(params[:id])
  end

  def team_update
    @admin_project = Project.find_by_code(params[:id])

    UsersProject.bulk_import(
      @admin_project, 
      params[:user_ids],
      params[:project_access],
      params[:repo_access]
    )

    redirect_to [:admin, @admin_project], notice: 'Project was successfully updated.'
  end

  def create
    @admin_project = Project.new(params[:project])
    @admin_project.owner = current_user

    if @admin_project.save
      redirect_to [:admin, @admin_project], notice: 'Project was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @admin_project = Project.find_by_code(params[:id])

    owner_id = params[:project].delete(:owner_id)

    if owner_id 
      @admin_project.owner = User.find(owner_id)
    end

    if @admin_project.update_attributes(params[:project])
      redirect_to [:admin, @admin_project], notice: 'Project was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @admin_project = Project.find_by_code(params[:id])
    @admin_project.destroy

    redirect_to admin_projects_url
  end
end

app/controllers/projects_controller.rb
require File.join(Rails.root, 'lib', 'graph_commit')

class ProjectsController < ApplicationController
  before_filter :project, :except => [:index, :new, :create]
  layout :determine_layout

  # Authorize
  before_filter :add_project_abilities
  before_filter :authorize_read_project!, :except => [:index, :new, :create]
  before_filter :authorize_admin_project!, :only => [:edit, :update, :destroy]
  before_filter :require_non_empty_project, :only => [:blob, :tree, :graph]

  def index
    @limit, @offset = (params[:limit] || 16), (params[:offset] || 0)
    @projects = current_user.projects.limit(@limit).offset(@offset)
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(params[:project])
    @project.owner = current_user

    Project.transaction do
      @project.save!
      @project.users_projects.create!(:project_access => UsersProject::MASTER, :user => current_user)

      # when project saved no team member exist so 
      # project repository should be updated after first user add
      @project.update_repository
    end

    respond_to do |format|
      if @project.valid?
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  rescue Gitlabhq::Gitolite::AccessDenied
    render :js => "location.href = '#{errors_githost_path}'" and return
  rescue StandardError => ex
    @project.errors.add(:base, "Cant save project. Please try again later")
    respond_to do |format|
      format.html { render action: "new" }
      format.js
    end
  end

  def update
    respond_to do |format|
      if project.update_attributes(params[:project])
        format.html { redirect_to edit_project_path(project), :notice => 'Project was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  def show
    return render "projects/empty" unless @project.repo_exists? && @project.has_commits?
    limit = (params[:limit] || 10).to_i
    @activities = @project.activities(limit)
  end

  def files
    @notes = @project.notes.where("attachment != 'NULL'").order("created_at DESC").limit(100)
  end

  #
  # Wall
  #

  def wall
    return render_404 unless @project.wall_enabled

    @note = Note.new
    @notes = @project.common_notes.order("created_at DESC")
    @notes = @notes.fresh.limit(20)

    respond_to do |format|
      format.html
      format.js { respond_with_notes }
    end
  end

  def graph
    render_full_content
    @days_json, @commits_json = GraphCommit.to_graph(project)
  end

  def destroy
    # Disable the UsersProject update_repository call, otherwise it will be
    # called once for every person removed from the project
    UsersProject.skip_callback(:destroy, :after, :update_repository)
    project.destroy
    UsersProject.set_callback(:destroy, :after, :update_repository)

    respond_to do |format|
      format.html { redirect_to projects_url }
    end
  end

  protected

  def project
    @project ||= Project.find_by_code(params[:id])
  end

  def determine_layout
    if @project && !@project.new_record?
      "project"
    else
      "application"
    end
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def view_mode_style(type)
    cookies["project_view"] ||= "tile"
    cookies["project_view"] == type ? nil : "display:none"
  end

  def load_note_parent(id, type, project)
    case type
    when "Issue" then @project.issues.find(id)
    when "Commit" then @project.repo.commits(id).first
    when "Snippet" then @project.snippets.find(id)
    else
      true
    end
  rescue
    nil
  end

  def project_tab_class
    [:show, :files, :team, :edit, :update].each do |action|
      return "current" if current_page?(:controller => "projects", :action => action, :id => @project)
    end

    if controller.controller_name == "snippets" || 
     controller.controller_name == "hooks" ||
     controller.controller_name == "deploy_keys" ||
     controller.controller_name == "team_members"
     "current"
    end
  end

  def tree_tab_class
    controller.controller_name == "refs" ? 
     "current" : nil
  end

  def repository_tab_class
    #if controller.controller_name == "repositories" ||
      #controller.controller_name == "hooks" ||
      #controller.controller_name == "deploy_keys"
     #"current"
    #end
  end

  def commit_tab_class
    if controller.controller_name == "commits" || 
      controller.controller_name == "repositories" ||
      controller.controller_name == "protected_branches"
      "current"
    end
  end

  def branches_tab_class
    if current_page?(branches_project_repository_path(@project)) ||
      controller.controller_name == "protected_branches" ||
      current_page?(project_repository_path(@project))
      'active' 
    end
  end
end

app/views/projects/_feed.html.haml
- @activities.each do |update|
  .wll
    = link_to dashboard_feed_path(@project, update) do 
      - if update.kind_of? Note
        %p
          %strong
            - if update.target
              = update.target.class.name.titleize
              = truncate update.target.id.to_s, :length => 10
              commented
            - else 
              Project wall
          &ndash;
          = image_tag gravatar_icon(update.author_email), :class => "", :width => 16
          = truncate dashboard_feed_title(update), :length => 50
      - else 
        %p
          %strong
            = update.class.name.titleize
            = truncate update.id.to_s
          &ndash;
          = image_tag gravatar_icon(update.author_email), :class => "", :width => 16
          = truncate dashboard_feed_title(update), :length => 50

app/views/projects/_list.html.haml
%table.round-borders#projects-list
  %tr
    %th Name
    %th Path
    %th Code
    %th Web
    %th Git
    %th Admin
    %th Actions

  - @projects.each do |project|
    %tr{ :class => "project", :url => project_path(project) }
      %td
        = project.name
        .small-tags= tag_list project

      %td= truncate project.url_to_repo
      %td= project.code
      %td= check_box_tag "read",   1, project.readers.include?(current_user), :disabled => :disabled
      %td= check_box_tag "commit", 1, project.writers.include?(current_user), :disabled => :disabled
      %td= check_box_tag "admin",  1, project.admins.include?(current_user), :disabled => :disabled
      %td
        -if can? current_user, :admin_project, project
          = link_to 'Edit', edit_project_path(project), :class => "lbutton positive"
%br

app/views/projects/_tile.html.haml
- @projects.in_groups_of(2, false) do |projects|
  .row
    - projects.each_with_index do |project, i|
      %div.project_tile
        .title
          = link_to project_path(project) do
            %h3= truncate(project.name, :length => 28)
        .data
          %p
            %input{ :value => project.url_to_repo, :class => ['git-url', 'one_click_select', 'text', 'project_list_url'], :readonly => 'readonly' }
        .buttons
          %a.btn.info{:href => tree_project_ref_path(project, project.root_ref)} Browse code
          %a.btn{:href => project_commits_path(project)} Commits

app/views/projects/create.js.haml
- if @project.valid?
  :plain
    location.href = "#{project_path(@project, :notice => 'Project was successfully created.')}";
- else
  :plain
    $("#new_project").replaceWith("#{escape_javascript(render('form'))}");
    $('.ajax_loader').hide();

app/views/projects/edit.html.haml
= render "project_head"
%h3 Edit Project
%hr
= render "projects/form"
%div{ :class => "ajax_loader",  :style => "display:none;height:200px;"}
  %center
    = image_tag "ajax-loader.gif", :class => "append-bottom"
    %h3.prepend-top Saving project &amp; repository. Please wait...

:javascript
  $(function(){
    $("#project_name").live("change", function(){
      var slug = slugify($(this).val());
      $("#project_code").val(slug);
      $("#project_path").val(slug);
    });
  });

  function slugify(text) {
    return text.replace(/[^-a-zA-Z0-9]+/g, '_').toLowerCase();
  }

  $(function(){
    $('.edit_project').live('ajax:before', function() {
      $(this).hide();
      $('.ajax_loader').show();
    });
    $('form #project_default_branch').chosen();
  })

app/views/projects/empty.html.haml
- if current_user.require_ssh_key?
  .alert-message.block-message.error
    %ul
      %li You have no ssh keys added yo tour profile.
      %li You wont be able to pull/push repository. 
      %li Visit profile &rarr; keys and add public key of every machine you want to use for work with gitlabhq. 

.alert-message.block-message.error
  %ul.alert_holder
    %li You should push repository to proceed.
    %li After push you will be able to browse code, commits etc. 

- bash_lexer = Pygments::Lexer[:bash]
%div.git-empty
  %h3 Git global setup:
  - setup_str = ["git config --global user.name \"#{current_user.name}\"", 
    "git config --global user.email  \"#{current_user.email}\""].join("\n")
  = raw bash_lexer.highlight(setup_str, :lexer => 'bash', :options => {:encoding => 'utf-8'})

  %br
  %br
  %h3 Create Repository
  - repo_setup_str = ["mkdir #{@project.path}",
    "cd #{@project.path}",
    "git init", 
    "touch README",
    "git add README",
    "git commit -m 'first commit'",
    "git remote add origin #{@project.url_to_repo}",
    "git push -u origin master"].join("\n")

  = raw bash_lexer.highlight(repo_setup_str)

  %br
  %br
  %h3 Existing Git Repo?
  - exist_repo_setup_str = ["cd existing_git_repo",
    "git remote add origin #{@project.url_to_repo}",
    "git push -u origin master"].join("\n")
  = raw bash_lexer.highlight(exist_repo_setup_str)

app/views/projects/files.html.haml
= render "project_head"
- unless @notes.empty?
  %table.zebra-striped.borders
    - @notes.each do |note|
      %tr
        %td
          %a{:href => note.attachment.url}
            = image_tag gravatar_icon(note.author_email), :class => "left", :width => 16
            &nbsp;
            = note.attachment_identifier
        %td  
          Added
          = time_ago_in_words(note.created_at)
          ago
- else 
  .notice_holder
    %li All files attached to project wall, issues etc will be displayed here

app/views/projects/graph.html.haml
%h3 Network Graph
%hr
#holder.graph.well

:javascript
  var chunk1={commits:#{@commits_json}};
  var days=#{@days_json};
  initGraph();
  $(function(){
    branchGraph($("#holder")[0]);
  });

app/views/projects/index.html.haml
%h3
  Projects
  %small= "( #{current_user.projects.count} )"
%hr
- unless @projects.empty?
  %div.content_list= render "tile"

  -# If projects requris paging
  -# We add ajax loader & init script
  - if @projects.count == @limit
    .loading{ :style => "display:none;"}
      %center= image_tag "ajax-loader.gif"

    :javascript
      $(function(){
        Pager.init(#{@limit});
      });
- else
  %h2 Nothing here

app/views/projects/index.js.haml
:plain
  Pager.append(#{@projects.count}, "#{escape_javascript(render(:partial => 'projects/tile'))}");

app/views/projects/show.html.haml
= render "project_head"
%h3
  = @project.name
  - if can? current_user, :download_code, @project
    = link_to "Download", archive_project_repository_path(@project), :class => "btn small right"
.back_link
  = link_to projects_path do 
    &larr; To projects list
%hr
.alert-message.block-message.warning
  .input
    .input-prepend
      %span.add-on git clone
      = text_field_tag :project_clone, @project.url_to_repo, :class => "xlarge one_click_select git_clone_url"

= simple_format @project.description
- unless @activities.blank?
  .ui-box
    %h5.cgray Recent Activity
    .content_list= render "feed"

app/views/projects/team.html.haml
= render "project_head"

- if can? current_user, :admin_team_member, @project
  .alert-message.block-message
    = link_to new_project_team_member_path(@project), :class => "btn small right", :title => "New Team Member" do 
      New Team Member
    %p Ream more about project permissions #{link_to "here", help_permissions_path, :class => "vlink"}
    %p To open team member profile - click on avatar. 


= render :partial => "team", :locals => {:project => @project}

app/views/projects/tree.js.haml
:plain
  $("#tree-holder table").hide("slide", { direction: "left" }, 150, function(){
    $("#tree-holder").html("#{escape_javascript(render(:partial => "tree", :locals => {:repo => @repo, :commit => @commit, :tree => @tree}))}");
    $("#tree-holder table").show("slide", { direction: "right" }, 150);
  });

app/views/projects/wall.js.haml
= render "notes/load"